config/routes.rb
Rails.application.routes.draw do
  get '/swagger' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'admin/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'devise/sessions#new'

  namespace :admin do
    resource :dashboard, only: :show
    get '/dashboard/chart/:type/(:parent)', to: 'dashboards#chart'
    resources :zones, except: [ :destroy, :show ]
    get '/zones/export/:id', to: 'zones#export', as: :zone_export
    resources :sections, except: [ :destroy, :show ]
    get '/sections/export/:id', to: 'sections#export', as: :section_export
    resources :squares, except: [ :destroy ]
    get '/squares/export/:id', to: 'squares#export', as: :square_export
    resources :voters
    resources :promoters, except: [:edit, :update]
    resources :sympathizers, except: [:show, :new, :create]
    resources :voter_documents, except: [ :edit, :destroy, :update ]
    get '/voter_documents/define_import/:id', to: 'voter_documents#define_import', as: :define_voter_document_import
    post '/voter_documents/import/:id', to: 'voter_documents#import', as: :import_voter_document
    resources :messages, except: [ :edit, :destroy, :update ]
    resources :notes, only: :index
  end

  get '/voter_passwords/edit', to: 'voter_passwords#edit'
  put '/voter_passwords/update', to: 'voter_passwords#update'
  get '/voter_passwords/success', to: 'voter_passwords#success'
  get '/voter_passwords/not_found', to: 'voter_passwords#not_found'

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :voters, only: [:update]
      resource :managements, only: [:create]
      resource :activities, only: [:create]
      mount_devise_token_auth_for 'Voter', at: 'auth', skip: [:omniauth_callbacks], controllers: {
        registrations:  'overrides/registrations',
        sessions:  'overrides/sessions',
        passwords: 'overrides/passwords'
      }
    end

  end
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  # devise modules
  # +  # Include default devise modules.
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable
  include DeviseTokenAuth::Concerns::User

  # Audio recording field for uploading with Carrierwave
  mount_uploader :audio, AudioUploader

  # Associations
  has_many :zones,    class_name: 'Zone',    foreign_key: :coordinator_id
  has_many :sections, class_name: 'Section', foreign_key: :coordinator_id
  has_many :squares,  class_name: 'Square',  foreign_key: :coordinator_id
  has_many :sympathizers, class_name: 'Voter',  foreign_key: :promoter_id
  has_many :contacts, class_name: 'Voter',  foreign_key: :added_by_id
  has_many :notes
  belongs_to :square
  belongs_to :promoter, class_name: 'Voter'

  # Validations
  validates_presence_of :name, :f_last_name, :street, :ext_num, 
    :neighborhood, :gender
  validates_presence_of :role, if: :created_from_app?
  validates :email, uniqueness: true, allow_nil: true
  validates :electoral_number, uniqueness: true, allow_nil: true

  # Callbacks
  before_validation :add_rand_password, on: :create
  before_validation :add_default_role, on: :create, if: Proc.new { |v| v.role.nil? }
  before_validation :set_uid
  before_validation :set_role, if: :created_from_app?
  after_save :assign_area_by_role, if: :created_from_app?
  before_save :welcome_email, if: :send_welcome_email?

  # Scopes
  scope :active, -> { where(active: true) }
  scope :with_roles, ->(roles){ where(role: roles) }
  scope :promoters, ->{ with_roles(PROMOTER) }
  scope :sympathizers, ->{ with_roles(SYMPATHIZER) }

  attr_accessor :from, :area_id, :old_area_id

  # constants
  ZONE_COORDINATOR = 1
  SECTION_COORDINATOR = 2
  SQUARE_COORDINATOR = 3
  PROMOTER = 4
  SYMPATHIZER = 5

  ROLES = {
    ZONE_COORDINATOR => I18n.t('voter.roles.zone_coordinator'),
    SECTION_COORDINATOR => I18n.t('voter.roles.section_coordinator'),
    SQUARE_COORDINATOR => I18n.t('voter.roles.square_coordinator'),
    PROMOTER => I18n.t('voter.roles.promoter'),
    SYMPATHIZER => I18n.t('voter.roles.sympathizer'),
  }

  IMPORT_FIELDS = %w(name f_last_name s_last_name birth_date gender street ext_num int_num neighborhood email electoral_number phone_number social_network)
  GROUPS = %w(group1 group2 group3 group4 group5)

  def token_validation_response
    {
      id: id,
      role: role,
      areas: areas_with_subareas
    }
  end

  def role_name
    ROLES[self.role]
  end

  def full_name
    "#{name} #{f_last_name} #{s_last_name}"
  end

  def address
    "#{street} #{ext_num} #{int_num} #{neighborhood}"
  end

  def areas
    case role
    when ZONE_COORDINATOR
      self.zones
    when SECTION_COORDINATOR
      self.sections
    when SQUARE_COORDINATOR
      self.squares
    when PROMOTER
      self.sympathizers
    else
      []
    end
  end

  def areas_with_subareas
    case role
    when ZONE_COORDINATOR
      zones.with_childrens
    when SECTION_COORDINATOR
      sections.with_childrens
    else
      []
    end
  end

  def self.allowed_zone_coordinators
    with_roles([ZONE_COORDINATOR, PROMOTER, SYMPATHIZER])
  end

  def self.allowed_section_coordinators
    with_roles([SECTION_COORDINATOR, PROMOTER, SYMPATHIZER])
  end

  def self.allowed_square_coordinators
    with_roles([SQUARE_COORDINATOR, PROMOTER, SYMPATHIZER])
  end

  def self.build_search(params)
    search(
      name_or_f_last_name_or_s_last_name_like: params[:name], 
      address_like: params[:address], 
      role_equals: params[:role],
      active_equals: params[:active],
      square_id_equals: params[:square],
      promoter_id_equals: params[:promoter]
    ).result
  end

  def add_promoter(params)
    self.role = PROMOTER
    self.square_id = params[:square_id]
    self.promoter_id = nil
    save
  end

  def remove_promoter
    remove_promoter_from_sympathizers
    self.role = SYMPATHIZER
    self.square_id = nil
    save
  end

  def add_sympathizer(params)
    self.role = SYMPATHIZER
    self.square_id = params[:square_id]
    self.promoter_id = params[:promoter_id]
    save
  end

  def remove_sympathizer
    self.role = SYMPATHIZER
    self.square_id = nil
    self.promoter_id = nil
    save
  end

  def reassign_role(role)
    return unless self.areas.size.zero?
    self.role = role
    self.square_id = nil
    self.promoter_id = nil
    self.save
  end

  def self.sympathizers_count
    with_roles([PROMOTER, SYMPATHIZER]).count
  end

  def self.coordinators_count
    with_roles([ZONE_COORDINATOR, SECTION_COORDINATOR, SQUARE_COORDINATOR]).count
  end

  def email_required?
    false
  end

  def self.find_or_new(params)
    if params[:email] || params[:electoral_number] || params[:id]
      voter = get_voter(params)
      build_voter(voter, params)
    else
      Voter.new(params)
    end
  end

  def set_device_token(device_token)
    Voter.where(device_token: device_token).update_all(device_token: nil)
    self.device_token = device_token
  end

  def self.by_area(type, ids)
    case(type)
    when 'zones'
      by_zones(ids)
    when 'sections'
      by_sections(ids)
    when 'squares'
      by_squares(ids)
    end
  end

  def self.by_zones(zone_ids)
    voters = joins(square: [section: :zone]).where('zones.id IN (?) AND voters.device_token IS NOT NULL', zone_ids).pluck(:id)
    coordinators = Zone.coordinators(zone_ids)
    voters + coordinators
  end

  def self.by_sections(sections_ids)
    voters = joins(square: :section).where('sections.id IN (?)', sections_ids).pluck(:id)
    coordinators = Section.coordinators(sections_ids)
    voters + coordinators
  end

  def self.by_squares(squares_ids)
    voters = joins(:square).where('square.id IN (?)', squares_ids).pluck(:id)
    coordinators = Square.coordinators(squares_ids)
    voters + coordinators
  end

  private
    def set_uid
      return unless self.uid.blank? || self.email_changed?
      self.uid = self.email
    end

    def set_role
      return if !self.role_changed? && area_id == old_area_id
      add_default_role if self.area_id.nil?
    end

    def assign_area_by_role
      case(self.role)
      when 2
        section = Section.find_by(id: area_id) 
        return add_default_role if section.nil?
        section.coordinator_id = self.id
        section.save
      when 3
        square = Square.find_by(id: area_id) 
        return add_default_role if square.nil?
        square.coordinator_id = self.id
        square.save
      when 4
        Voter.where(square_id: area_id).update_all(promoter_id: id)
        update(square_id: area_id)
      end
    end

    def remove_promoter_from_sympathizers
      sympathizers.update_all(promoter_id: nil)
    end

    def created_from_app?
      from == 'app'
    end

    def add_default_role
      self.role = SYMPATHIZER
    end

    def add_rand_password
      return unless self.password.blank?
      self.password = (0...10).map { (65 + rand(26)).chr }.join
    end

    def send_welcome_email?
      !email.blank? && created_from_app? && email_was != email
    end

    def welcome_email
      enc = Devise.token_generator.generate(self.class, :reset_password_token)
      update_columns(reset_password_token: enc[1], reset_password_sent_at: Time.now.utc)
      VoterMailer.download_app_email(self).deliver_now
    end

    def self.get_voter(params)
      if params[:id]
        Voter.find_by(id: params[:id])
      else
        return nil unless params[:email] || params[:electoral_number]
        where_params = {}
        where_params[:email] = params[:email] if params[:email]
        where_params[:electoral_number] = params[:electoral_number] if params[:electoral_number]
        find_by(where_params)
      end
    end

    def self.build_voter(voter, params)
      if voter.nil?
        Voter.new(params)
      else
        voter.assign_attributes(params)
        voter
      end
    end
end

app/controllers/admin/voters_controller.rb
class Admin::VotersController < Admin::AdminBaseController
  before_action :search_form, only: :index

  def index
    if params[:q].present?
      @voters = Voter.build_search(params[:q]).order('street asc').page(params[:page])
    else
      @voters = Voter.all.order('street asc').page(params[:page])
    end
  end

  def new
    @voter = Voter.new
  end

  def create
    @voter = Voter.new(voter_permit)
    if @voter.save
      flash.now[:success] = 'Se creó la persona satisfactoriamente'
      redirect_to admin_voters_path
    else
      flash.now[:danger] = 'Hubo un error al crear la persona'
      render :new
    end
  end

  def edit
    @voter = Voter.find(params[:id])
  end

  def update
    @voter = Voter.find(params[:id])
    if @voter.update(voter_permit)
      flash.now[:success] = 'Se actualizó la persona satisfactoriamente'
      redirect_to admin_voters_path
    else
      flash.now[:danger] = 'Hubo un error al editar la persona'
      render :edit
    end
  end

  def show
    @voter = Voter.find(params[:id])
  end

  private
    def voter_permit
      params[:voter].delete(:password) if params[:voter][:password].blank?
      params.require(:voter).permit(:name, :f_last_name, 
        :s_last_name, :birth_date, :gender, :street, :ext_num,
        :int_num, :neighborhood, :email, :electoral_number, :phone_number,
        :social_network, :password, :active
      )
    end

    def search_form
      # @sections = Section.active.includes(:zone)
      @q = params[:q] ||= {}
    end
end

app/controllers/api/v1/voters_controller.rb
class Api::V1::VotersController < Api::V1::ApiBaseController
  respond_to :json

  def update
    voter = Voter.find_or_new(voter_permit)
    if voter.save
      render json: voter, status: :ok
    else
      render json: voter.errors, status: :unprocessable_entity
    end
  end

  private
    def voter_permit
      params[:voter][:added_by_id] = current_api_v1_voter.id
      params[:voter][:from] = 'app'

      params.require(:voter).permit(
        :name,
        :f_last_name,
        :s_last_name,
        :latitude,
        :longitude,
        :street,
        :ext_num,
        :int_num,
        :neighborhood,
        :phone_number,
        :social_network,
        :area_id,
        :role,
        :added_by_id,
        :email,
        :birth_date,
        :electoral_number,
        :active,
        :from,
        :gender,
        :id,
        :old_area_id
      )
    end
end

app/helpers/voters_helper.rb
module VotersHelper
  def roles_options
    Voter::ROLES.map{|k,v| [v,k]}
  end

  # def areas_name(voter)
  def in_charge_of_name(voter)
    areas = voter.areas
    return if areas.blank?
    if voter.role == Voter::PROMOTER
      areas.map(&:full_name).join('-')
    else
      areas.map(&:with_parents_name).join('-')
    end
  end

  def group_values(fields)
    fields.map{|field| [I18n.t("voter.#{field}"), field]}
  end
end

app/views/admin/voters/_form.html.haml
.panel.panel-default
  .panel-body
    = simple_form_for [:admin, @voter], html: {class:  'form-horizontal', validate: false, 'data-parsley-validate' => true } do |f|
      .col-lg-6
        = f.input :name, label: 'Nombre', required: true
        = f.input :f_last_name, label: 'Primer apellido', required: true
        = f.input :s_last_name, label: 'Segundo apellido'
        = f.input :birth_date, label: 'Fecha de nacimiento'
        = f.input :street, label: 'Calle', required: true
        = f.input :ext_num, label: 'Numero Ext.', required: true
        = f.input :int_num, label: 'Numero Int.'
        = f.input :neighborhood, label: 'Colonia', required: true
        = f.input :gender, as: :select, collection: ['Masculino', 'Femenino'], label: 'Sexo', include_blank: 'Ninguno', input_html: {data: {tool: 'select2'}}
        = f.input :email, label: 'Correo electronico'
        = f.input :password, as: :password, label: 'Contraseña'
        = f.input :electoral_number, label: 'Clave electoral'
        = f.input :phone_number, label: 'Telefono'
        = f.input :social_network, label: 'Red social'
        = f.input :active, as: :boolean
        .form-group
          = f.button :submit, 'Guardar', class: 'btn btn-success'

app/views/admin/voters/edit.html.haml
%h3
  Editar persona
  .pull-right
    = link_to 'Lista de personas', admin_voters_path, class: 'btn btn-default pull-right'

= render partial: 'form'

app/views/admin/voters/index.html.haml
= content_for :javascript do
  = javascript_include_tag 'panels', 'jquery.storageapi'

%h3
  Personas
  .pull-right
    = link_to 'Crear persona', new_admin_voter_path, class: 'btn btn-success'

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading.panel-heading-collapsed
        Buscar
        = link_to 'javascript:void(0)', data: {tool: 'panel-collapse',
          toggle: 'tooltip'}, class: 'pull-right' do
          %em.fa.fa-plus
      .panel-wrapper.collapse
        = simple_form_for :q, { url: admin_voters_path, method: :get, defaults: {required: false} } do |f|
          .panel-body
            .row
              .col-lg-4
                = f.input :name, input_html: {value: @q[:name]}, label: 'Nombre'
              .col-lg-4
                = f.input :address, input_html: {value: @q[:address]}, label: 'Dirección'
              .col-lg-4
                = f.input :role, as: :select, collection: roles_options, selected: @q[:role], include_blank: 'Todos', label: 'Rol', input_html: {data: {tool: 'select2'}}
            .row
              .col-lg-4
                = f.input :active, as: :select, collection: active_options, selected: @q[:active], include_blank: 'Todos', label: 'Activo', input_html: {data: {tool: 'select2'}}
          .panel-footer
            = f.button :submit, value: 'Buscar', class: 'btn btn-primary'
            %span.pull-right
              = link_to 'Mostrar todos', admin_voters_path, class: 'btn btn-default'

.row
  .col-lg-12  
    .panel.panel-default 
      .panel-body
        - if @voters.empty?
          %h4
            No hay personas registradas
        - else
          %table.table.table-responsive.table-bordered.table-hover
            %thead
              %tr
                %th Nombre
                %th Dirección
                %th Rol
                %th Encargado de
                %th Activa
                %th
            %tbody
              - @voters.each do |voter|
                %tr
                  %td
                    = voter.full_name.titleize
                  %td
                    = voter.try(:address)
                  %td
                    = voter.try(:role_name)
                  %td
                    = in_charge_of_name(voter)
                  %td
                    = active_label(voter)
                  %td
                    = link_to 'Ver', admin_voter_path(voter.id)
                    |
                    = link_to 'Editar', edit_admin_voter_path(voter.id)
    = paginate @voters

app/views/admin/voters/new.html.haml
%h3
  Nueva persona
  .pull-right
    = link_to 'Lista de personas', admin_voters_path, class: 'btn btn-default pull-right'

= render partial: 'form'

app/views/admin/voters/show.html.haml
.panel.panel-default
  .panel-heading
    %b
      = @voter.full_name.titleize

  .panel-body
    .col-md-12
      .col-md-6
        %div
          %b
            Nombre: 
          = @voter.name.titleize
        %div
          %b
            Primer apellido: 
          = @voter.f_last_name.titleize
        %div
          %b
            Segundo apellido: 
          = @voter.s_last_name.titleize
        %div
          %b
            Rol: 
          = @voter.role_name.titleize
        - if @voter.role != Voter::SYMPATHIZER
          %div
            %b
              Encargado de: 
            = in_charge_of_name(@voter)
        %div
          %b
            Dirección: 
          = @voter.address.titleize
        %div
          %b
            Correo electronico: 
          = @voter.email
        %div
          %b
            Clave electoral: 
          = @voter.electoral_number
        %div
          %b
            Telefono: 
          = @voter.phone_number
        %div
          %b
            Red social: 
          = @voter.social_network
        %div
          %b
            Activo: 
          = active_label(@voter)

        

.col-md-12.text-right.bottom
  = link_to 'Lista de personas', admin_voters_path, class: 'btn btn-default'