config/routes.rb
Rails.application.routes.draw do
  get '/swagger' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'admin/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'devise/sessions#new'

  namespace :admin do
    resource :dashboard, only: :show
    get '/dashboard/chart/:type/(:parent)', to: 'dashboards#chart'
    resources :zones, except: [ :destroy, :show ]
    get '/zones/export/:id', to: 'zones#export', as: :zone_export
    resources :sections, except: [ :destroy, :show ]
    get '/sections/export/:id', to: 'sections#export', as: :section_export
    resources :squares, except: [ :destroy ]
    get '/squares/export/:id', to: 'squares#export', as: :square_export
    resources :voters
    resources :promoters, except: [:edit, :update]
    resources :sympathizers, except: [:show, :new, :create]
    resources :voter_documents, except: [ :edit, :destroy, :update ]
    get '/voter_documents/define_import/:id', to: 'voter_documents#define_import', as: :define_voter_document_import
    post '/voter_documents/import/:id', to: 'voter_documents#import', as: :import_voter_document
    resources :messages, except: [ :edit, :destroy, :update ]
    resources :notes, only: :index
  end

  get '/voter_passwords/edit', to: 'voter_passwords#edit'
  put '/voter_passwords/update', to: 'voter_passwords#update'
  get '/voter_passwords/success', to: 'voter_passwords#success'
  get '/voter_passwords/not_found', to: 'voter_passwords#not_found'

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :voters, only: [:update]
      resource :managements, only: [:create]
      resource :activities, only: [:create]
      mount_devise_token_auth_for 'Voter', at: 'auth', skip: [:omniauth_callbacks], controllers: {
        registrations:  'overrides/registrations',
        sessions:  'overrides/sessions',
        passwords: 'overrides/passwords'
      }
    end

  end
end

app/models/square.rb
class Square < ActiveRecord::Base
  belongs_to :section
  belongs_to :coordinator, class_name: Voter, foreign_key: :coordinator_id
  has_many :voters
  
  validates :name, presence: true, length: { maximum: 100 }
  validates :section_id, presence: true
  validates_associated :section

  scope :active, ->{ joins(section: :zone).where("squares.active = true
    AND sections.active = true AND zones.active = true") }
  scope :by_section, ->(section_id){ where(section_id: section_id) }
  
  after_save :assing_voter_coordination

  def with_parents_name
    "#{section.with_parents_name} - #{name}"
  end

  def with_section_name
    "#{section.name} - #{name}"
  end

  def self.build_chart(section_name)
    labels = []
    data = []
    section = Section.find_by(name: section_name)
    unless section.nil?
      section.squares.includes(:voters).each do |square|
        labels << square.name
        data << square.voters.size
      end
    end
    [labels, data]
  end

  def self.build_search(params)
    search(
      name_like: params[:name], 
      section_id_equals: params[:section],
      coordinator_id_equals: params[:coordinator],
      active_equals: params[:active]
    ).result
  end

  def self.coordinators(squares_ids)
    where(id: squares_ids).pluck(:coordinator_id)
  end

  private
    def assing_voter_coordination
      return unless self.coordinator_id_changed?
      remove_old_coordination
      return if self.coordinator_id.nil?
      self.coordinator.reassign_role(Voter::SQUARE_COORDINATOR)
    end

    def remove_old_coordination
      voter = Voter.find_by(id: self.coordinator_id_was)
      return if voter.nil?
      voter.reassign_role(Voter::SYMPATHIZER)
    end
end

app/controllers/admin/squares_controller.rb
class Admin::SquaresController < Admin::AdminBaseController
  before_action :search_form, only: :index
  before_filter :get_sections, only: [:index, :new, :edit]

  def index
    if params[:q].present?
      @squares = Square.build_search(params[:q]).order('name asc').page(params[:page])
    else
      @squares = Square.all.includes(:coordinator, section: :zone).order('name asc').page(params[:page])
    end
  end

  def new
    @square = Square.new
    @coordinators = Voter.allowed_square_coordinators
  end

  def create
    @square = Square.new(square_permit)
    if @square.save
      flash.now[:success] = 'Se creó la manzana satisfactoriamente'
      redirect_to admin_squares_path
    else
      flash.now[:danger] = 'Hubo un error al crear la manzana'
      render :new
    end
  end

  def show
    @square = Square.find(params[:id])
  end

  def edit
    @square = Square.find(params[:id])
    @coordinators = Voter.allowed_square_coordinators
  end

  def update
    @square = Square.find(params[:id])
    if @square.update(square_permit)
      flash.now[:success] = 'Se actualizó la manzana satisfactoriamente'
      redirect_to admin_squares_path
    else
      flash.now[:danger] = 'Hubo un error al editar la manzana'
      render :edit
    end
  end

  def export
    @square = Square.includes(:voters).find(params[:id])
    @section = @square.section
    respond_to do |format|
      format.xlsx
    end
  end

  private
    def square_permit
      params.require(:square).permit(:name, 
        :section_id, :coordinator_id, :active)
    end

    def get_sections
      @sections = Section.all.includes(:zone)
    end

    def search_form
      @coordinators = Voter.with_roles(Voter::SQUARE_COORDINATOR)
      @q = params[:q] ||= {}
    end
end

app/controllers/api/v1/squares_controller.rb
class Api::V1::SquaresController < Api::V1::ApiBaseController
  before_action :authenticate_api_v1_voter!
  respond_to :json

  def index
    zone_id = params[:zone_id]
    section_id = params[:section_id]
    if zone_id
      squares = Square.where(zone_id: zone_id)
    elsif section_id
      squares = Square.where(section_id: section_id)
    else
      squares = Square.all
    end
    respond_with squares
  end

  swagger_controller :zones, "Squares Management", resource_path: "/api/v1"
  swagger_api :index do
    summary "Fetches all squares"
    notes "This lists all the squares, you can filter the squares per zone or section, if you send both values, the api will return by the zone filter since zone has high priority"
    param :query, :zone_id, :string, :optional, "Filter per zone_id"
    param :query, :section_id, :string, :optional, "Filter per section_id"
    param :header, 'access-token', :string, :required, 'Access token'
    param :header, 'token-type', :string, :required, 'Token type'
    param :header, 'client', :string, :required, 'Client'
    param :header, 'expiry', :string, :required, 'Expiry'
    param :header, 'uid', :string, :required, 'Email'
    response :unauthorized
    response :not_acceptable, "The request you made is not acceptable"
    response :requested_range_not_satisfiable
  end

end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/views/admin/squares/_form.html.haml
.panel.panel-default
  .panel-body
    = simple_form_for [:admin, @square], html: {class:  'form-horizontal', validate: false, 'data-parsley-validate' => true } do |f|
      .col-lg-6
        = f.association :section, collection: @sections, value_method: :id, label_method: :with_parents_name, label: 'Sección', include_blank: false, required: true, input_html: {data: {tool: 'select2'}}
        = f.input :name, input_html: { maxlength: 100 }, label: 'Nombre', required: true
        = f.association :coordinator, collection: @coordinators, value_method: :id, label_method: :full_name, label: 'Coordinador', include_blank: 'Ninguno', input_html: {data: {tool: 'select2'}}
        = f.input :active, as: :boolean
        .form-group
          = f.button :submit, 'Guardar', class: 'btn btn-success'

app/views/admin/squares/edit.html.haml
%h3
  Editar manzana
  .pull-right
    = link_to 'Lista de manzanas', admin_squares_path, class: 'btn btn-default pull-right'

= render partial: 'form'

app/views/admin/squares/index.html.haml
= content_for :javascript do
  = javascript_include_tag 'panels', 'jquery.storageapi'

%h3
  Manzanas
  .pull-right
    = link_to 'Crear zona', new_admin_square_path, class: 'btn btn-success'

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading.panel-heading-collapsed
        Buscar
        = link_to 'javascript:void(0)', data: {tool: 'panel-collapse',
          toggle: 'tooltip'}, class: 'pull-right' do
          %em.fa.fa-plus
      .panel-wrapper.collapse
        = simple_form_for :q, { url: admin_squares_path, method: :get, defaults: {required: false} } do |f|
          .panel-body
            .row
              .col-lg-4
                = f.input :name, input_html: {value: @q[:name]}, label: 'Nombre'
              .col-lg-4
                = f.input :section, as: :select, collection: @sections, label_method: :with_parents_name, value_method: :id, selected: @q[:section], include_blank: 'Todas', label: 'Zona/Sección', input_html: {data: {tool: 'select2'}}
              .col-lg-4
                = f.input :coordinator, as: :select, collection: @coordinators, label_method: :full_name, value_method: :id, selected: @q[:coordinator], include_blank: 'Todos', label: 'Coordinador', input_html: {data: {tool: 'select2'}}
            .row
              .col-lg-4
                = f.input :active, as: :select, collection: active_options, selected: @q[:active], include_blank: 'Todos', label: 'Activo', input_html: {data: {tool: 'select2'}}
          .panel-footer
            = f.button :submit, value: 'Buscar', class: 'btn btn-primary'
            %span.pull-right
              = link_to 'Mostrar todos', admin_squares_path, class: 'btn btn-default'

.row
  .col-lg-12  
    .panel.panel-default 
      .panel-body
        - if @squares.empty?
          %h4
            No hay manzanas registradas
        - else
          %table.table.table-responsive.table-bordered.table-hover
            %thead
              %tr
                %th Nombre
                %th Zona/Sección
                %th Coordinador
                %th Activa
                %th
            %tbody
              - @squares.each do |square|
                %tr
                  %td
                    = square.name.titleize
                  %td
                    = square.section.with_parents_name.titleize
                  %td
                    = coordinator_name(square)
                  %td
                    = active_label(square)
                  %td
                    = link_to 'Ver', admin_square_path(square.id)
                    |
                    = link_to 'Editar', edit_admin_square_path(square.id)
                    |
                    = link_to 'Exportar', admin_square_export_path(square.id, format: :xlsx)
          = paginate @squares

app/views/admin/squares/new.html.haml
%h3
  Nueva manzana
  .pull-right
    = link_to 'Lista de manzanas', admin_squares_path, class: 'btn btn-default pull-right'

= render partial: 'form'

app/views/admin/squares/show.html.haml
.panel.panel-default
  .panel-heading
    %b
      = @square.name.titleize

  .panel-body
    .col-md-12
      .col-md-6
        %div
          %b
            Sección: 
          = @square.section.with_parents_name
        %div
          %b
            Coordinador:
          = coordinator_name(@square)
        %div
          %b
            Activa:
          = active_label(@square)
    .col-md-12
      .col-md-6
        Simpatizantes
        %ol
          - @square.voters.each do |voter|
            %li
              = voter.full_name

.col-md-12.text-right.bottom
  = link_to 'Lista de manzanas', admin_squares_path, class: 'btn btn-default'