config/routes.rb
Rails.application.routes.draw do
  get '/swagger' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'admin/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'devise/sessions#new'

  namespace :admin do
    resource :dashboard, only: :show
    get '/dashboard/chart/:type/(:parent)', to: 'dashboards#chart'
    resources :zones, except: [ :destroy, :show ]
    get '/zones/export/:id', to: 'zones#export', as: :zone_export
    resources :sections, except: [ :destroy, :show ]
    get '/sections/export/:id', to: 'sections#export', as: :section_export
    resources :squares, except: [ :destroy ]
    get '/squares/export/:id', to: 'squares#export', as: :square_export
    resources :voters
    resources :promoters, except: [:edit, :update]
    resources :sympathizers, except: [:show, :new, :create]
    resources :voter_documents, except: [ :edit, :destroy, :update ]
    get '/voter_documents/define_import/:id', to: 'voter_documents#define_import', as: :define_voter_document_import
    post '/voter_documents/import/:id', to: 'voter_documents#import', as: :import_voter_document
    resources :messages, except: [ :edit, :destroy, :update ]
    resources :notes, only: :index
  end

  get '/voter_passwords/edit', to: 'voter_passwords#edit'
  put '/voter_passwords/update', to: 'voter_passwords#update'
  get '/voter_passwords/success', to: 'voter_passwords#success'
  get '/voter_passwords/not_found', to: 'voter_passwords#not_found'

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :voters, only: [:update]
      resource :managements, only: [:create]
      resource :activities, only: [:create]
      mount_devise_token_auth_for 'Voter', at: 'auth', skip: [:omniauth_callbacks], controllers: {
        registrations:  'overrides/registrations',
        sessions:  'overrides/sessions',
        passwords: 'overrides/passwords'
      }
    end

  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :squares, dependent: :restrict_with_error
  belongs_to :zone
  belongs_to :coordinator, class_name: Voter, foreign_key: :coordinator_id

  validates :name, presence: true, length: { maximum: 100 }
  validates_associated :zone

  default_scope ->{ order('name asc') }
  scope :active, ->{ where(active: true, zones: { active: true}) }
  scope :by_zone, ->(zone_id){ where(zone_id: zone_id) }

  after_save :assing_voter_coordination

  def with_parents_name
    "#{zone.name} - #{name}"
  end

  def self.with_childrens
    includes(:squares).map do |section|
      {
        id: section.id,
        name: section.name,
        squares: section.squares
      }
    end
  end

  def self.coordinators(sections_ids)
    coordinators = []
    where(id: sections_ids).includes(:squares).each do |section|
      coordinators << section.coordinator_id unless section.coordinator_id.nil?
      section.squares.each do |square|
        coordinators << square.coordinator_id unless square.coordinator_id.nil?
      end
    end
    coordinators
  end

  def self.build_chart(zone_name)
    labels = []
    data = []
    zone = Zone.find_by(name: zone_name)
    unless zone.nil?
      zone.sections.includes(:squares).each do |section|
        labels << section.name
        data << section.squares.size
      end
    end
    [labels, data]
  end

  def self.build_search(params)
    search(
      name_like: params[:name], 
      zone_id_equals: params[:zone],
      coordinator_id_equals: params[:coordinator],
      active_equals: params[:active]
    ).result
  end

  private
    def assing_voter_coordination
      return unless self.coordinator_id_changed?
      remove_old_coordination
      return if self.coordinator_id.nil?
      self.coordinator.reassign_role(Voter::SECTION_COORDINATOR)
    end

    def remove_old_coordination
      voter = Voter.find_by(id: self.coordinator_id_was)
      return if voter.nil?
      voter.reassign_role(Voter::SYMPATHIZER)
    end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminBaseController
  before_action :search_form, only: :index
  before_action :get_zones, only: [:index, :new, :edit]

  def index
    if params[:q].present?
      @sections = Section.build_search(params[:q]).order('name asc').page(params[:page])
    else
      @sections = Section.all.includes(:coordinator, :zone).order('name asc').page(params[:page])
    end
  end

  def new
    @section = Section.new
    @coordinators = Voter.allowed_section_coordinators
  end

  def create
    @section = Section.new(section_permit)
    if @section.save
      flash.now[:success] = 'Se creó la sección satisfactoriamente'
      redirect_to admin_sections_path
    else
      flash.now[:danger] = 'Hubo un error al crear la sección'
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
    @coordinators = Voter.allowed_section_coordinators
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_permit)
      flash.now[:success] = 'Se actualizó la sección satisfactoriamente'
      redirect_to admin_sections_path
    else
      flash.now[:danger] = 'Hubo un error al editar la sección'
      render :edit
    end
  end

  def export
    @section = Section.includes(squares: :voters).find(params[:id])
    respond_to do |format|
      format.xlsx
    end
  end

  private
    def section_permit
      params.require(:section).permit(:name, :zone_id, :coordinator_id, :active)
    end

    def get_zones
      @zones = Zone.all
    end

    def search_form
      @coordinators = Voter.with_roles(Voter::SECTION_COORDINATOR)
      @q = params[:q] ||= {}
    end
end

app/controllers/api/v1/sections_controller.rb
class Api::V1::SectionsController < Api::V1::ApiBaseController
  before_action :authenticate_api_v1_voter!
  respond_to :json

  def index
    zone_id = params[:zone_id]
    if zone_id
      sections = Section.where(zone_id: zone_id)
    else
      sections = Section.all
    end
    respond_with sections
  end

  swagger_controller :zones, "Sections Management", resource_path: "/api/v1"
  swagger_api :index do
    summary "Fetches all sections"
    notes "This lists all the sections"
    param :query, :zone_id, :string, :optional, "Filter per zone_id"
    param :header, 'access-token', :string, :required, 'Access token'
    param :header, 'token-type', :string, :required, 'Token type'
    param :header, 'client', :string, :required, 'Client'
    param :header, 'expiry', :string, :required, 'Expiry'
    param :header, 'uid', :string, :required, 'Email'
    response :unauthorized
    response :not_acceptable, "The request you made is not acceptable"
    response :requested_range_not_satisfiable
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/sections/_form.html.haml
.panel.panel-default
  .panel-body
    = simple_form_for [:admin, @section], html: {class:  'form-horizontal', validate: false, 'data-parsley-validate' => true } do |f|
      .col-lg-6
        = f.association :zone, collection: @zones, value_method: :id, label_method: :name, label: 'Zona', include_blank: false, required: true, input_html: {data: {tool: 'select2'}}
        = f.input :name, input_html: { maxlength: 100 }, label: 'Nombre', required: true
        = f.association :coordinator, collection: @coordinators, value_method: :id, label_method: :full_name, label: 'Coordinador', include_blank: 'Ninguno', input_html: {data: {tool: 'select2'}}
        = f.input :active, as: :boolean
        .form-group
          = f.button :submit, 'Guardar', class: 'btn btn-success'

app/views/admin/sections/edit.html.haml
%h3
  Editar sección
  .pull-right
    = link_to 'Lista de secciones', admin_sections_path, class: 'btn btn-default pull-right'

= render partial: 'form'

app/views/admin/sections/index.html.haml
= content_for :javascript do
  = javascript_include_tag 'panels', 'jquery.storageapi'

%h3
  Secciones
  .pull-right
    = link_to 'Crear zona', new_admin_section_path, class: 'btn btn-success'

.row
  .col-lg-12
    .panel.panel-default
      .panel-heading.panel-heading-collapsed
        Buscar
        = link_to 'javascript:void(0)', data: {tool: 'panel-collapse',
          toggle: 'tooltip'}, class: 'pull-right' do
          %em.fa.fa-plus
      .panel-wrapper.collapse
        = simple_form_for :q, { url: admin_sections_path, method: :get, defaults: {required: false} } do |f|
          .panel-body
            .row
              .col-lg-4
                = f.input :name, input_html: {value: @q[:name]}, label: 'Nombre'
              .col-lg-4
                = f.input :zone, as: :select, collection: @zones, label_method: :name, value_method: :id, selected: @q[:zone], include_blank: true, label: 'Zona', include_blank: 'Todas', input_html: {data: {tool: 'select2'}}
              .col-lg-4
                = f.input :coordinator, as: :select, collection: @coordinators, label_method: :full_name, value_method: :id, selected: @q[:coordinator], include_blank: 'Todos', label: 'Coordinador', input_html: {data: {tool: 'select2'}}
            .row
              .col-lg-4
                = f.input :active, as: :select, collection: active_options, selected: @q[:active], include_blank: 'Todos', label: 'Activo', input_html: {data: {tool: 'select2'}}
          .panel-footer
            = f.button :submit, value: 'Buscar', class: 'btn btn-primary'
            %span.pull-right
              = link_to 'Mostrar todos', admin_zones_path, class: 'btn btn-default'

.row
  .col-lg-12  
    .panel.panel-default 
      .panel-body
        - if @sections.empty?
          %h4
            No hay secciones registradas
        - else
          %table.table.table-responsive.table-bordered.table-hover
            %thead
              %tr
                %th Nombre
                %th Zona
                %th Coordinador
                %th Activo
                %th
            %tbody
              - @sections.each do |section|
                %tr
                  %td
                    = section.name.titleize
                  %td
                    = section.zone.name.titleize
                  %td
                    = coordinator_name(section)
                  %td
                    = active_label(section)
                  %td
                    = link_to 'Manzanas', admin_squares_path(q: {section: section.id})
                    |
                    = link_to 'Editar', edit_admin_section_path(section.id)
                    |
                    = link_to 'Exportar', admin_section_export_path(section.id, format: :xlsx)
        = paginate @sections

app/views/admin/sections/new.html.haml
%h3
  Nueva sección
  .pull-right
    = link_to 'Lista de secciones', admin_sections_path, class: 'btn btn-default pull-right'

= render partial: 'form'