config/routes.rb
Rails.application.routes.draw do
  get '/swagger' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')
  devise_for :admins

  devise_scope :admin do
    authenticated :admin do
      root 'admin/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'devise/sessions#new'

  namespace :admin do
    resource :dashboard, only: :show
    get '/dashboard/chart/:type/(:parent)', to: 'dashboards#chart'
    resources :zones, except: [ :destroy, :show ]
    get '/zones/export/:id', to: 'zones#export', as: :zone_export
    resources :sections, except: [ :destroy, :show ]
    get '/sections/export/:id', to: 'sections#export', as: :section_export
    resources :squares, except: [ :destroy ]
    get '/squares/export/:id', to: 'squares#export', as: :square_export
    resources :voters
    resources :promoters, except: [:edit, :update]
    resources :sympathizers, except: [:show, :new, :create]
    resources :voter_documents, except: [ :edit, :destroy, :update ]
    get '/voter_documents/define_import/:id', to: 'voter_documents#define_import', as: :define_voter_document_import
    post '/voter_documents/import/:id', to: 'voter_documents#import', as: :import_voter_document
    resources :messages, except: [ :edit, :destroy, :update ]
    resources :notes, only: :index
  end

  get '/voter_passwords/edit', to: 'voter_passwords#edit'
  put '/voter_passwords/update', to: 'voter_passwords#update'
  get '/voter_passwords/success', to: 'voter_passwords#success'
  get '/voter_passwords/not_found', to: 'voter_passwords#not_found'

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :voters, only: [:update]
      resource :managements, only: [:create]
      resource :activities, only: [:create]
      mount_devise_token_auth_for 'Voter', at: 'auth', skip: [:omniauth_callbacks], controllers: {
        registrations:  'overrides/registrations',
        sessions:  'overrides/sessions',
        passwords: 'overrides/passwords'
      }
    end

  end
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |name, msg|
  - if ['notice', 'alert'].include?(name)
    - name = (name == 'alert') ? 'danger' : 'success'
  - if msg.is_a?(String)
    %div(class="alert alert-#{name} alert-dismissible")
      %button.close(type="button" data-dismiss="alert" aria-label="Close")
        %span(aria-hidden="true") &times;
      = msg
  - elsif msg.is_a?(Hash)
    %ul{class: "alert alert-#{name} alert-dismissible"}
      - msg.each do |key, value|
        %li
          %span
            %strong= "#{key}:"
            - value.each do |text|
              = text

app/views/layouts/_header.html.haml
%header.topnavbar-wrapper
  %nav.navbar.topnavbar{role: 'navigation'}
    .navbar-header
      = link_to 'logo', root_path, class: 'navbar-brand'
    .nav-wrapper
      %ul.nav.navbar-nav
        %li
          = link_to '#', class: 'visible-xs sidebar-toggle',
            data: {'toggle-state' => 'aside-toggled', 
            'no-persist' => 'true'} do
            %em.fa.fa-navicon

app/views/layouts/_sidebar.html.haml
%aside.aside
  .aside-inner
    #nav.sidebar{'data-sidebar-anyclick-close' => ''}
      %ul.nav
        %li{class: active_menu_option('dashboard')}
          = link_to root_path do
            %span
              Panel de control
        %li.nav-heading
          Areas
        %li{class: active_menu_option('zones')}
          = link_to admin_zones_path do
            %span
              Zonas
        %li{class: active_menu_option('sections')}
          = link_to admin_sections_path do
            %span
              Secciones
        %li{class: active_menu_option('squares')}
          = link_to admin_squares_path do
            %span
              Manzanas
        %li.nav-heading
          Roles
        %li{class: active_menu_option('promoters')}
          = link_to admin_promoters_path do
            %span
              Promotores
        %li{class: active_menu_option('sympathizers')}
          = link_to admin_sympathizers_path do
            %span
              Simpatizantes
        %li.nav-heading
          Personas
        %li{class: active_menu_option('voters')}
          = link_to admin_voters_path do
            %span
              Personas
        %li{class: active_menu_option('voter_documents')}
          = link_to admin_voter_documents_path do
            %span
              Importar
        %li.nav-heading
          Comunicación
        %li{class: active_menu_option('messages')}
          = link_to admin_messages_path do
            %span
              Mensajes
        %li{class: active_menu_option('notes', {'note_type' => 'management'})}
          = link_to admin_notes_path(note_type: 'management') do
            %span
              Gestión
        %li{class: active_menu_option('notes', {'note_type' => 'activity'})}
          = link_to admin_notes_path(note_type: 'activity') do
            %span
              Actividades
        %li
          = link_to destroy_admin_session_path, method: :delete do
            %span
              Salir

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Votantes
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1'}
    = csrf_meta_tags
    = stylesheet_link_tag 'application'
    = yield :stylesheet
  %body
    .wrapper
      - unless current_admin.nil?
        = render 'layouts/header'
        = render 'layouts/sidebar'
        %section
          .content-wrapper
            = render 'layouts/flash_messages'
            = yield
      - else
        .content-wrapper
          = render 'layouts/flash_messages'
          = yield
      = javascript_include_tag 'application'
      = yield :javascript

app/views/layouts/devise_token.html.haml
!!!
%html
  %title Votantes
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %body
    #header
      = render 'layouts/flash_messages'
    #content.container
      = yield
    #footer.container
    = javascript_include_tag 'application'
    = yield :javascript